/**
 * Salesforce
 * @author              Diego Rincón (DR) href=<diego.rincon@ext.mpsa.com>
 * Project:             PSA - Customer First
 * Description:         Unit tests to validate the behavior of LeadManualAssignment class.
 *
 * Changes (version)
 * -------------------------------------------------------------------------------------------------
 *              No.     Date            Author                  Description
 *              ----    ------------    --------------------    ------------------------------------
 * @version     1.0     2019-07-02      Diego Rincón (DR)       Class creation. Code coverage: 100%
 *
 */
@isTest
private class LeadManualAssignmentTest {
    @isTest static void testMethod1(){
        LeadManualAssignment.getUserData();
    }

}